services:
  - type: web
    name: erp-saas
    env: python
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn --timeout 60 run:app"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: DATABASE_URL
        value: sqlite:///database.db
