"""Criacao das tabelas Tenant, Transaction e TaxDetail

Revision ID: e1ef0cd00511
Revises: 
Create Date: 2026-06-06 23:10:38.394000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ef0cd00511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tax_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tax_name', sa.String(length=50), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_details_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_details_transaction_id'))

    op.drop_table('tax_details')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_id'))

    op.drop_table('transactions')
    op.drop_table('tenants')
    # ### end Alembic commands ###
